FROM adoptopenjdk/openjdk11:x86_64-alpine-jdk-11.0.11_9-slim
ARG JAR_FILE
COPY ${JAR_FILE} funding-data-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar funding-data-service-0.0.1-SNAPSHOT.jar"]